### ISSUE TITLE
Product Options 

### ISSUE THREAD

**Issue by oliverheywood451** [ordercloud-api/ngx-shopper#34] opened 2018-06-28 21:16 UTC
As a buyer user 
- When I try to add a product to the cart ( from anywhere in the app ) that has a spec with multiple values a modal pops up.
- The modal has a dropdown for each spec and an option in the dropdown for each option.
- If the spec has a default option, that option is selected in the dropdown to start
- A button at the bottom of the modal called 'Add to Card' is disabled until all dropdowns have a selection.
- When the button is clicked, the modal is dismissed.

**Comment by crhistianramirez** [comment] 2018-07-17 18:09
Closing since this one is a duplicate of #81

**Closed by crhistianramirez** 2018-07-17 18:09 UTC
Labels: buyer
